CREATE TABLE post (
	id				BIGINT generated by default as identity (start with 1),
	title			VARCHAR NOT NULL,
	description		VARCHAR NOT NULL,
	created_at  	DATETIME NOT NULL,
	updated_at  	DATETIME
);
